name: 'fish-shop/run-fishtape-tests'
description: 'A GitHub action for running fishtape tests'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  pattern:
    description: 'File name pattern'
    required: false
    default: '**.fish'
  raw-output:
    description: 'Produce raw TAP output'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - uses: fish-shop/install-plugin@2d758540a20e90f474c98de7a22d3a0f9ddad1b2 # v2.2.6
      with:
        plugin-manager: fisher
        plugins: jorgebucaran/fishtape
    - name: Install tap-diff
      run: npm install -g tap-diff
      shell: fish {0}
    - name: Run fishtape tests
      run: |
        set -gx TERM xterm-256color
        set -gx FORCE_COLOR 2
        switch ${{ inputs.raw-output }}
            case true
                fishtape ${{ inputs.pattern }}
            case '*'
                fishtape ${{ inputs.pattern }} | tap-diff
        end
      shell: fish {0}
