name: 'fish-shop/run-fishtape-tests'
description: 'A GitHub action for running fishtape tests'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  patterns:
    description: 'File patterns to match against when running tests'
    required: false
    default: '**.fish'
  raw-output:
    description: 'Produce raw TAP output'
    required: false
    default: 'false'
outputs:
  total:
    description: "Total number of tests executed"
    value: ${{ steps.run-fishtape-tests.outputs.total }}
  passed:
    description: "Number of tests passed"
    value: ${{ steps.run-fishtape-tests.outputs.passed }}
  failed:
    description: "Number of tests failed"
    value: ${{ steps.run-fishtape-tests.outputs.failed }}
runs:
  using: 'composite'
  steps:
    - name: Install fisher
      uses: fish-shop/install-plugin@02f698ac752778153f33d90a19ff07e6c49fca23 # v2.3.2
      with:
        plugin-manager: fisher
        plugins: jorgebucaran/fishtape
    - name: Install tap-diff
      run: npm install -g tap-diff
      shell: fish {0}
    - name: Run fishtape tests
      id: run-fishtape-tests
      env:
        PATTERNS: ${{ inputs.patterns }}
        RAW_OUTPUT: ${{ inputs.raw-output }}
      run: |
        set -gx TERM xterm-256color
        set -gx FORCE_COLOR 2

        set raw_output (string escape --no-quoted -- $RAW_OUTPUT)

        for pattern in (string split --no-empty -- " " $PATTERNS)
            set -l escaped (string escape --style=script --no-quoted -- $pattern)
            set -l escaped (string replace -r -a -- '\\\([?*{}])' '$1' $escaped)
            eval set -a files $escaped
        end

        switch $raw_output
            case true
                fishtape $files | tee output
            case false
                fishtape $files | tee output | tap-diff
            case '*'
                echo "Unrecognised raw output option: '$raw_output'" >&2
                exit 1
        end

        set total (tail -n 4 output | sed -rn 's/^[[:digit:]]\.\.([[:digit:]]+)$/\1/p')
        set passed (tail -n 4 output | sed -rn 's/^# pass ([[:digit:]]+)$/\1/p')
        set failed (tail -n 4 output | sed -rn 's/^# fail ([[:digit:]]+)$/\1/p')

        for param in total passed failed
          if test -z "$$param"
            set $param 0
          end
        end

        echo "total=$total" >> "$GITHUB_OUTPUT"
        echo "passed=$passed" >> "$GITHUB_OUTPUT"
        echo "failed=$failed" >> "$GITHUB_OUTPUT"
      shell: fish {0}
    - name: Generate job summary
      env:
        TOTAL: ${{ steps.run-fishtape-tests.outputs.total }}
        PASSED: ${{ steps.run-fishtape-tests.outputs.passed }}
        FAILED: ${{ steps.run-fishtape-tests.outputs.failed }}
      run: |
        if test "$FAILED" = "0"
          set result ":white_check_mark: Pass"
        else
          set result ":x: Fail"
        end

        echo "### Test results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Test result :microscope: | Passed :white_check_mark: | Failed :x: |" >> $GITHUB_STEP_SUMMARY
        echo "|--------------------------|---------------------------|------------|" >> $GITHUB_STEP_SUMMARY
        echo "| $result                  | $PASSED                   | $FAILED    |" >> $GITHUB_STEP_SUMMARY
      shell: fish {0}
