name: 'fish-shop/run-fishtape-tests'
description: 'A GitHub action for running fishtape tests'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  patterns:
    description: 'File patterns to match against when running tests'
    required: false
    default: '**.fish'
  raw-output:
    description: 'Produce raw TAP output'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Install fisher
      uses: fish-shop/install-plugin@9b1d802d389c0226fe523ef0d214f3e50ec31087 # v2.3.1
      with:
        plugin-manager: fisher
        plugins: jorgebucaran/fishtape
    - name: Install tap-diff
      run: npm install -g tap-diff
      shell: fish {0}
    - name: Run fishtape tests
      env:
        PATTERNS: ${{ inputs.patterns }}
        RAW_OUTPUT: ${{ inputs.raw-output }}
      run: |
        set -gx TERM xterm-256color
        set -gx FORCE_COLOR 2

        set raw_output (string escape --no-quoted -- $RAW_OUTPUT)

        for pattern in (string split --no-empty -- " " $PATTERNS)
            set -l escaped (string escape --style=script --no-quoted -- $pattern)
            set -l escaped (string replace -r -a -- '\\\([?*{}])' '$1' $escaped)
            eval set -a files $escaped
        end

        switch $raw_output
            case true
                fishtape $files
            case false
                fishtape $files | tap-diff
            case '*'
                echo "Unrecognised raw output option: '$raw_output'" >&2; and exit 1
        end
      shell: fish {0}
