name: Dependency Review
on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  dependency-review:
    name: Dependency Review
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/dependency-review.yml@bb57c462d9d13fe7839ee1a3194387789970f874 # v1.14.27
